# Generated by Django 4.2.29 on 2026-04-03 11:47

import apps.reports.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(default=apps.reports.models.generate_ref_id, editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('water', '💧 Water Leak'), ('electricity', '⚡ Electricity Fault'), ('roads', '🛣️ Road Damage'), ('waste', '🗑️ Waste Collection'), ('sewage', '🚿 Sewage'), ('lighting', '💡 Street Lighting'), ('other', '📋 Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='logged', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Issue Report',
                'verbose_name_plural': 'Issue Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reports.issuereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reports.issuereport')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('issue', 'session_key')},
            },
        ),
    ]
